jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Upgrade pip and install uv and dependencies
        run: |
          python -m pip install --upgrade pip
          pip install uv gunicorn uvicorn
          uv venv
          uv pip install -r requirements.txt
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Run linter
        run: make lint

      - name: Run tests
        run: make test

      - name: Run test coverage
        run: make test-cov

      - name: SonarQubeScan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=IlyaLysenkov-Hexlet_python-project-522
            -Dsonar.organization=ilyalysenkov-hexlet
            -Dsonar.python.coverage.reportPaths=coverage.xml
            -Dsonar.coverage.exclusions=tests/**
            -Dsonar.exclusions=tests/**
